language: java
script:
- mvn clean package
deploy:
  provider: heroku
  api_key:
    secure: mT837FM3O8aPM9DkjuGrKsPZA06NGjqPWE1h/v+ZH1sJ+NoDK4pC1qMNaSJsi9NZAKT5bCtMByiPg6bIGjOAdBpBf3doXihpK387RLEfyn1IN7qjKFLXVGOCp/GWSWbjf07rjTIOZ6R4cUb73ZNk3h/tRs9GWXB/0/trYPB6dbWJexcH4f/HjVSzsxLVVgFJxmVb5q4s92qn2U2wsq1C7pDNZaWuiDLcUgIvb16EAbfKxBil5PY0fUOXAewlRh4bfhqb5XI8Wlb1F4cDaFm3K5WPLlfRn4NA4KG1QaRbElFP0un07yJFLj3Xu3/FYgePEWTL7LiBbQC4B3Z+6voOYvYvomA2GmkbLd6KpmTm0F2L3S+BIGr812GcPx/3rLGeOM/b47AZC1OQg/j2PtaiOC16eYcOeEwJLYEcCHJQQW5vWjv8bkHtekiMDNvyRMCG8SJfSbQ4SZBk/3Q+tW6IJlDxQeSdh2bpmUN5G8O6gIvBRUldPhIFvqoEAjzOuoCDDTdnRs4Fs46v2/EguhGpsZYj9UP3y1SRPZ/x/dXyhc2GXh79zeB5dzyX4DAtH1mnkGOgUDiWffJ2iXCdOroO8sAgw4ROmssIw+wlfM4Fo+vuNNLl1jL7BU72hir1H8ICIYMpqvPtB/dD+vuQ/DNiQhxJEEh7fbkKAN1VGtfwq3k=
